// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJnZMrDriOgpAhzi7Ou185VPaKSQscQr4',
    appId: '1:1078034189985:web:4c12b219855057ef1aaae0',
    messagingSenderId: '1078034189985',
    projectId: 'tugas-week-4',
    authDomain: 'tugas-week-4.firebaseapp.com',
    storageBucket: 'tugas-week-4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSBljDYXbJX4heC6NGosJOfMoO0LVyVyY',
    appId: '1:1078034189985:android:f246ee527c16d8651aaae0',
    messagingSenderId: '1078034189985',
    projectId: 'tugas-week-4',
    storageBucket: 'tugas-week-4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCudUvW3DoQh8l7JvaAYV3pbVEDkyx5cPc',
    appId: '1:1078034189985:ios:107034c2c03e40c91aaae0',
    messagingSenderId: '1078034189985',
    projectId: 'tugas-week-4',
    storageBucket: 'tugas-week-4.firebasestorage.app',
    iosBundleId: 'com.example.utsKurban1123150007',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCudUvW3DoQh8l7JvaAYV3pbVEDkyx5cPc',
    appId: '1:1078034189985:ios:107034c2c03e40c91aaae0',
    messagingSenderId: '1078034189985',
    projectId: 'tugas-week-4',
    storageBucket: 'tugas-week-4.firebasestorage.app',
    iosBundleId: 'com.example.utsKurban1123150007',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJnZMrDriOgpAhzi7Ou185VPaKSQscQr4',
    appId: '1:1078034189985:web:81ead188bf6c924a1aaae0',
    messagingSenderId: '1078034189985',
    projectId: 'tugas-week-4',
    authDomain: 'tugas-week-4.firebaseapp.com',
    storageBucket: 'tugas-week-4.firebasestorage.app',
  );
}
